### ISSUE TITLE
Compiled micrate binary does nothing when ran.

### ISSUE THREAD

**Issue by elorest** [juanedi/micrate#15]
I can compile micrate just fine but when I run `micrate up` it doesn't give me any sort of message or run my migrations. I'm on OSX sierra with crystal 0.21.1

**Comment by juanedi** [comment]
Hi @elorest! Sorry about the delay.

Which file are you compiling? If it's `src/micrate.cr` then it will do nothing because there is no "main" code being run. If that's the case, you should create a file as specified in the README, explicitly running the CLI and setting up your connection URL:

```crystal
#! /usr/bin/env crystal
#
# To build a standalone command line client, require the
# driver you wish to use and use `Micrate::Cli`.
#

require "micrate"
require "pg"

Micrate::DB.connection_url = "postgresql://..."
Micrate::Cli.run
```

Hope that helps, please let me know if it worked.

**Comment by elorest** [comment]
Oh ok. That makes sense. For some reason I was expecting it to look in
database.yml or at least give me an error. Thanks

Isaac Sloan - isaacsloan.com
Artisan Rails Architect
1391 S Slate Canyon Dr.
Provo, Ut 84606
Cell: (435)-669-5005
